### ISSUE TITLE
Failed to build Docker image

### ISSUE THREAD

**Issue by fedecerno** [google/oss-fuzz-gen#115]
When running the command ./run_all_experiments.py -y ./benchmark-sets/comparison/tinyxml2.yaml --model='gpt-3.5-turbo', the program fails with the following error:

***Failed to build image for tinyxml2-_zn8tinyxml210xmlprinter10visitentererkns_10xmlelementepkns_12xmlattributee-01.***

The log file in the build folder contains the following text:

***ERROR: invalid tag "gcr.io/oss-fuzz/tinyxml2-_zn8tinyxml210xmlprinter10visitentererkns_10xmlelementepkns_12xmlattributee-01": invalid reference format.***

This is caused by Docker having issues with the substring ***'-_'***.

To work around this issue, I inserted the character ***1*** as the first character of the ***name*** field in the .yaml file. 

"functions":
    - "name": "***1***_ZN8tinyxml210XMLPrinter10VisitEnterERKNS_10XMLElementEPKNS_12XMLAttributeE"

**Comment by DonggeLiu** [comment]
Thanks for reporting the issue, @fedecerno!
#111 attempts to capture and fix all these errors. This appears to be an undocumented Docker tag naming rule that disallows dashes (`-`) followed by underscore (`_`) (and `-`s after `_`).

As discussed in the email, manually inserting chars between those two symbols will not fix all benchmarks and all cases (e.g., `_-` is also invalid) : )

----

Your email mentioned the error shows up in a different place:
```
gcr.io/oss-fuzz/tinyxml2-zn8tinyxml210xmlelement12setattributeepkcs2_-01
```
I will try to reproduce it and come up with a fix later.

**Comment by DonggeLiu** [comment]
Hi @fedecerno , could you please check if https://github.com/google/oss-fuzz-gen/pull/125 fixes the error you discovered and if there are more unhandled corner cases?
Thanks!
