### ISSUE TITLE
Failed to generate coverage report

### ISSUE THREAD

**Issue by fedecerno** [google/oss-fuzz-gen#116]
When running the command ***./run_all_experiments.py -y ./benchmark-sets/comparison/tinyxml2.yaml --model='gpt-3.5-turbo***, I encounter the following error: 

***Failed to generate coverage for tinyxml2-1_zn8tinyxml210xmlprinter10visitentererkns_10xmlelementepkns_12xmlattributee-01:*** 
***b"docker: Error response from daemon: driver failed programming external connectivity on endpoint peaceful_northcutt (3cbb3adaf2b435dbe77012b48d83f6464ea4c8c640ec356fcdb375fbcaf59381):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 32827 -j DNAT --to-destination 172.17.0.2:0 ! -i docker0: iptables v1.8.7 (nf_tables): Port `0' not valid\n\nTry `iptables -h' or 'iptables --help' for more information.\n (exit status 2)).\n"***
***b'INFO:__main__:Running: docker run --rm --privileged --shm-size=2g --platform linux/amd64 -e FUZZING_ENGINE=libfuzzer -e HELPER=True -e FUZZING_LANGUAGE=c++ -e PROJECT=tinyxml2-1_zn8tinyxml210xmlprinter10visitentererkns_10xmlelementepkns_12xmlattributee-01 -e SANITIZER=coverage -e COVERAGE_EXTRA_ARGS= -e ARCHITECTURE=x86_64 -p 0:0 -v /home/cernera/Desktop/PhD/fuzzer-llm/oss-fuzz-gen/result-prova-replica-risultati/output-tinyxml2-1_zn8tinyxml210xmlprinter10visitentererkns_10xmlelementepkns_12xmlattributee/corpora/01.cpp:/corpus/xmltest -v /tmp/tmpem1yc_np/build/out/tinyxml2-1_zn8tinyxml210xmlprinter10visitentererkns_10xmlelementepkns_12xmlattributee-01:/out -t gcr.io/oss-fuzz-base/base-runner coverage xmltest.\nERROR:__main__:Failed to generate clang code coverage report.\n'***

The issue is related to the port number. The value 0 is not a valid port number.

**Comment by DonggeLiu** [comment]
Thanks for reporting the issue, @fedecerno!
Could you please check if https://github.com/google/oss-fuzz-gen/pull/113 fixes this on your machine?

It changes 0 to an empty string, which should have the same effect but avoids using 0 directly.

**Comment by fedecerno** [comment]
Yes, I confirm that #113 fix this problem.

**Comment by DonggeLiu** [comment]
> Yes, I confirm that #113 fixes this problem.

Thanks!
