### ISSUE TITLE
Slef-Hosted LLM?

### ISSUE THREAD

**Issue by Tverous** [google/oss-fuzz-gen#133]
Hi,

Will it be possible to use self-hosted LLM like [Llama](https://llama.meta.com/), [CodeT5](https://github.com/salesforce/CodeT5), etc. in the future?

Thanks

**Comment by DonggeLiu** [comment]
Thanks @Tverous, the current should be able to support that.

You can add a model class at [`models.py`](https://github.com/google/oss-fuzz-gen/blob/main/llm_toolkit/models.py), give it a name, and pass the name to [the `--model` flag](https://github.com/google/oss-fuzz-gen/blob/main/run_all_experiments.py#L147). [`GPT`](https://github.com/google/oss-fuzz-gen/blob/main/llm_toolkit/models.py#L166) could be a good example of this.

Depending on the prompt structure of your model, you may need to overwrite prompt generation functions. Using the same `GPT` example, it overwrites a plain text prompt (used by Vertex AI) with [a JSON structured one](https://github.com/google/oss-fuzz-gen/blob/main/llm_toolkit/prompts.py#L92).

If your self-hosted LLM needs an alternative way to access, you can encapsulate that in a binary/script, and use the [`--ai-binary` flag](https://github.com/google/oss-fuzz-gen/blob/main/run_all_experiments.py#L140). For example, a binary/script that sends the prompt to an API and passes the response to OSS-Fuzz-Gen.

**Comment by DonggeLiu** [comment]
Please feel free to reopen this if my method above does not work for your case : )
