### ISSUE TITLE
Save reproducers found in experiments

### ISSUE THREAD

**Issue by DonggeLiu** [google/oss-fuzz-gen#156]
This will help us triage crashes in experiments.
We can save:
1. Fuzz target source code.
2. Fuzz target binary.
3. crash reproducer.
4. Link to the corresponding page in the report.

**Comment by DonggeLiu** [comment]
@oliverchang: Anything else we can/should save to assist triaging?

**Comment by oliverchang** [comment]
> @oliverchang: Anything else we can/should save to assist triaging?

Also the stacktrace / output from the target. This can help us filter out bad cases.

**Comment by DonggeLiu** [comment]
> > @oliverchang: Anything else we can/should save to assist triaging?
> 
> Also the stacktrace / output from the target. This can help us filter out bad cases.

Thanks, I presume this has been included in the result report page?
> 4. Link to the corresponding page in the report.

I can also save the log file.

**Comment by oliverchang** [comment]
> > > @oliverchang: Anything else we can/should save to assist triaging?
> > 
> > 
> > Also the stacktrace / output from the target. This can help us filter out bad cases.
> 
> Thanks, I presume this has been included in the result report page?

Yes, but a more automatable way to get just the stacktrace (I.e. a link that  we can set in a JSON result), that will make this a lot easier to analyze at  scale.
