### ISSUE TITLE
IndexError in builder_runner.py:194, _parse_fuzz_cov_info_from_libfuzzer_logs()

### ISSUE THREAD

**Issue by cjx10** [google/oss-fuzz-gen#241]
```
Traceback (most recent call last):
  File "/experiment/experiment/evaluator.py", line 209, in check_target
    return self.do_check_target(ai_binary, target_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/experiment/experiment/evaluator.py", line 259, in do_check_target
    build_result, run_result = self.builder_runner.build_and_run(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/experiment/experiment/builder_runner.py", line 721, in build_and_run
    run_result.semantic_check = self._parse_libfuzzer_logs(f)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/experiment/experiment/builder_runner.py", line 239, in _parse_libfuzzer_logs
    initcov, donecov, lastround = self._parse_fuzz_cov_info_from_libfuzzer_logs(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/experiment/experiment/builder_runner.py", line 194, in _parse_fuzz_cov_info_from_libfuzzer_logs
    initcov = int(line.split('cov: ')[1].split(' ft:')[0])
                  ~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
Full experiment log available [here](https://pantheon.corp.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22oss-fuzz%22%0Aresource.labels.location%3D%22us-central1-c%22%0Aresource.labels.cluster_name%3D%22llm-experiment%22%0Aresource.labels.namespace_name%3D%22default%22%0Alabels.k8s-pod%2Fbatch_kubernetes_io%2Fcontroller-uid%3D%221ec7d455-00bb-4913-9937-9115e35a455c%22%20severity%3E%3DWARNING;summaryFields=:false:32:beginning;cursorTimestamp=2024-05-01T04:39:17.949112480Z;aroundTime=2024-05-01T04:39:16.428742349Z;duration=PT15S?mods=logs_tg_prod&project=oss-fuzz)

**Comment by cjx10** [comment]
run log triggered this error: `gs://oss-fuzz-gcb-experiment-run-logs/Result-reports/ofg-pr/2024-05-01-238-jim-comparison/results/output-hiredis-rediscommand/logs/run/04.c-F0.log`
```
#2	INITED exec/s: 0 rss: 34Mb
```

**Comment by DonggeLiu** [comment]
Should have been fixed by https://github.com/google/oss-fuzz-gen/pull/276/files.
@cjx10 could you please double-check the latest exp log (05-19) and close this?

Thanks!

**Comment by cjx10** [comment]
Confirm fixed, thanks Dongge :)
