### ISSUE TITLE
oss-fuzz-gen video tutorial

### ISSUE THREAD

**Issue by aaronatp** [google/oss-fuzz-gen#520]
Would any of the authors consider doing a video tutorial? The usage guide has helped me a little bit but there aren't many great resources online showing how to use oss-fuzz-gen :/

I really want to use the tool and a video tutorial would help me figure out how to use it a lot quicker :)

**Comment by aaronatp** [comment]
Hello, would this be possible? I believe many other people would also help a lot of other people

**Comment by DavidKorczynski** [comment]
Yeah, I'm happy to make one

**Comment by aaronatp** [comment]
That would be amazing thank you :)

**Comment by aaronatp** [comment]
Hi @DavidKorczynski any updates by chance?

**Comment by DavidKorczynski** [comment]
I'm working on this, will let you know here when I have an update

**Comment by CityOfLight77** [comment]
@DavidKorczynski waiting for it

**Comment by DavidKorczynski** [comment]
Please see here for a video tutorial giving a brief introduction to OSS-Fuzz-gen: https://www.youtube.com/watch?v=RR7CUyOtYXY

I have it in the plans to make more, but I'd think this is a good tutorial for running OFG on simple intuitive example.
